dotfiles_repo: https://github.com/rob121/dotfiles.git

mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
  - { id: 595191960, name: "Copy Clip" }
  - { id: 405399194, name: "Kindle" }
  - { id: 472226235, name: "LanScan" }
  - { id: 1176074088, name: "Termius - SSH client" }
  - { id: 803453959, name: "Slack" }
  - { id: 926036361, name: "Last Pass" }
  - { id: 1354318707, name: "Core Tunnel 2.5.1" }

homebrew_cask_apps:
  - cyberduck
  - chromedriver
  - bitbar
  - google-chrome
  - google-drive-file-stream
  - goland
  - favro
  - iterm2
  - docker
  - handbrake
  - transmit
  - paragon-ntfs
  - vagrant
  - notable
  - postman
  - displaylink
  - viscosity
  - vlc



homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - lrzsz
  - jq
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - sshuttle
  - pv
  - wget
  - wrk
